"""add operator_name and nullable operator_id to production

Revision ID: 4ca1cf24b9b4
Revises: 352af3e85112
Create Date: 2026-04-03 14:41:31.040128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca1cf24b9b4'
down_revision = '352af3e85112'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('operator_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.execute("""
        UPDATE production
        SET operator_name = (SELECT name FROM operator WHERE operator.id = production.operator_id)
        WHERE operator_name IS NULL AND operator_id IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production', schema=None) as batch_op:
        batch_op.alter_column('operator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('operator_name')

    # ### end Alembic commands ###
