from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8ab5c676fa'
down_revision = '320d5fc9f1d6'
branch_labels = None
depends_on = None


def _table_exists(table_name: str) -> bool:
    """Evita fallar si la tabla ya existe (p. ej. creada por db.create_all()
    en un entorno local antes de que esta migración se aplique)."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('product_change'):
        op.create_table('product_change',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_persona', sa.String(length=100), nullable=False),
        sa.Column('cliente', sa.String(length=150), nullable=True),
        sa.Column('orden_compra', sa.String(length=100), nullable=True),
        sa.Column('factura', sa.String(length=100), nullable=True),
        sa.Column('comentario', sa.String(length=255), nullable=True),
        sa.Column('fecha', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not _table_exists('product_change_item'):
        op.create_table('product_change_item',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_change_id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('cantidad', sa.Float(), nullable=False),
        sa.Column('unidad', sa.String(length=20), nullable=False),
        sa.Column('tipo', sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(['product_change_id'], ['product_change.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists('product_change_item'):
        op.drop_table('product_change_item')
    if _table_exists('product_change'):
        op.drop_table('product_change')
    # ### end Alembic commands ###