"""Agregar horas opcionales por producto

Revision ID: 70496d8af825
Revises: b1316a52a862
Create Date: 2026-08-18 18:16:29.981750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70496d8af825'
down_revision = 'b1316a52a862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_product', schema=None) as batch_op:
        batch_op.drop_column('horas')

    # ### end Alembic commands ###
