"""Add dispatch and dispatch_product tables

Revision ID: 767af3ded285
Revises: 7e4ee255df50
Create Date: 2025-08-06 22:29:45.127438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767af3ded285'
down_revision = '7e4ee255df50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.String(length=50), nullable=False),
    sa.Column('chofer_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['chofer_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dispatch_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch_product')
    op.drop_table('dispatch')
    # ### end Alembic commands ###
