"""Remove email from Client model

Revision ID: 7e4ee255df50
Revises: 31ef3157dd88
Create Date: 2025-08-06 21:59:04.146038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4ee255df50'
down_revision = '31ef3157dd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('client_email_key'), type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('client_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
