"""remove driver with associated dispatches

Revision ID: 81483af3be40
Revises: 4b19a3ca5a71
Create Date: 2026-01-24 19:14:21.746292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81483af3be40'
down_revision = '4b19a3ca5a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = {c['name'] for c in inspector.get_columns('dispatch')}

    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        if 'chofer_name' not in columns:
            batch_op.add_column(sa.Column('chofer_name', sa.String(length=100), nullable=True))

    # Dialect-specific SQL for populating chofer_name (solo si la columna existe o fue agregada)
    if 'chofer_name' not in columns or True:  # Ejecutar siempre para seguridad si hay datos nuevos
        dialect = conn.dialect.name
        if dialect == 'postgresql':
            op.execute(
                """
                UPDATE dispatch
                SET chofer_name = driver.name
                FROM driver
                WHERE dispatch.chofer_id = driver.id
                AND (chofer_name IS NULL OR chofer_name = '')
                """
            )
        elif dialect == 'sqlite':
            op.execute(
                """
                UPDATE dispatch
                SET chofer_name = (SELECT name FROM driver WHERE id = dispatch.chofer_id)
                WHERE chofer_name IS NULL OR chofer_name = ''
                """
            )

    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        # Solo alterar si es necesario (puedes dejar como está o agregar chequeos)
        batch_op.alter_column('chofer_name',
               existing_type=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('chofer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('dispatch_chofer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'driver', ['chofer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dispatch_chofer_id_fkey'), 'driver', ['chofer_id'], ['id'])
        batch_op.alter_column('chofer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('chofer_name',
               existing_type=sa.String(length=100),
               nullable=True)  # Hacer nullable antes de dropear (por robustez)
        batch_op.drop_column('chofer_name')

    # ### end Alembic commands ###