"""add avatar_url and update_code to user

Revision ID: 8a9ab7812ca5
Revises: 96e1f9e66cfa
Create Date: 2025-08-08 22:49:40.779544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9ab7812ca5'
down_revision = '96e1f9e66cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_code', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('update_code')

    # ### end Alembic commands ###
