"""Add status column to dispatch

Revision ID: ab6e8d3c685e
Revises: 767af3ded285
Create Date: 2025-08-07 00:01:57.513347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab6e8d3c685e'
down_revision = '767af3ded285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispatch', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
